export const SET_ERROR = 'SET_ERROR'
export const SET_USER = 'SET_USER'
export const SET_RANKING = 'SET_RANKING'
export const SET_RANKING_CONFIG = 'SET_RANKING_CONFIG'
export const SET_RANK = 'SET_RANK'